/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-10-20 01:44:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.neusoft.entity.*;

public final class AfterIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/LuoJiSiWei_Shoping/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/Login2_02/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1506583284000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("com.neusoft.entity");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/index.css\" />   \r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/AfterIndex.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/xiala.css\" />\r\n");
      out.write("\t\t <script type=\"text/javascript\" src=\"js/_ll.js\" ></script>\r\n");
      out.write("\t\t <script type=\"text/javascript\" src=\"js/_iframe.js\" ></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<form action=\"gwcServlet\">\r\n");
      out.write("\t\t<input type=\"text\" name=\"name1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${namePsw.loginname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t<div id=\"top\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"AfterIndex.jsp\">首页</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"denglu\"><a href=\"index.jsp\">注销</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"OrderPage.jsp\">管理我的消息</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"gwc.jsp\">购物车</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">联系我们</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"ssl\">\r\n");
      out.write("\t\t\t<div class=\"spzs\">商品展示</div>\r\n");
      out.write("\t\t\t<div class=\"button\"><input type=\"text\" placeholder=\"充电宝\"/><button>搜索</button></div>\r\n");
      out.write("\t\t\t<div><a href=\"gwc.jsp\">我的购物车</a></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t    \r\n");
      out.write("\t    <div id=\"qpsp\">\r\n");
      out.write("\t    \t<p class=\"_p\">全部商品分类</p>\r\n");
      out.write("\t    \t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    <div id=\"shang_left\">\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \r\n");
      out.write("\t    \t<div id=\"lb_01\">\r\n");
      out.write("\t\t    <img id=\"_img\" onclick=\"_ll()\" src=\"img/chu.png\" width=\"30px\" height=\"30px\"/><p><a href=\"#\">电脑/笔记本</a></p>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t    \t<div id=\"shop_class\" >\r\n");
      out.write("\t    \t<ul>\r\n");
      out.write("\t    \t\t<li onclick=\"_iframe()\"><a href=\"#\">神州计算机</a></li>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">华硕计算机</a></li>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">联想计算机</a></li>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">惠普计算机</a></li>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">红旗计算机</a></li>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">苹果计算机</a></li>\r\n");
      out.write("\t    \t</ul>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t<div id=\"lb_01\">\r\n");
      out.write("\t\t    <img id=\"_img2\" onclick=\"_ll2()\" src=\"img/chu.png\" width=\"30px\" height=\"30px\"/><p><a href=\"#\">水果/蔬菜</a></p>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t    \t<div id=\"shop_class2\" >\r\n");
      out.write("\t    \t<ul>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">苹果</a></li>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">白菜</a></li>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">黄瓜</a></li>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">青菜</a></li>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">香蕉</a></li>\r\n");
      out.write("\t    \t\t<li><a href=\"#\">梨</a></li>\r\n");
      out.write("\t    \t</ul>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"geirenxx\">\r\n");
      out.write("\t    \t<p><a onclick=\"javascript:window.location.href='updateConsServlet?name1=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${namePsw.loginname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">修改密码</a></p>\r\n");
      out.write("\t    \t<p><a href=\"xgNickname.jsp\">修改个人消息</a></p>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"_iframe\">\r\n");
      out.write("\t\t\t<iframe id=\"_iframe_nr\" src=\"getProPage?pageNo=1&pageSize=7\"></iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
