/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-10-20 01:43:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.neusoft.entity.PageModel;
import com.neusoft.entity.Product;

public final class new_005fshangping_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/LuoJiSiWei_Shoping/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/Login2_02/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1506583284000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.neusoft.entity.PageModel");
    _jspx_imports_classes.add("com.neusoft.entity.Product");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/new_shangping.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/NewPage.css\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"css/app.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/demo.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/normalize.css\" />\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<p id=\"he_p\"><b>新品展示</b></p>\r\n");
      out.write("\t\t<div class=\"slider\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"slider-img\" >\r\n");
      out.write("\t\t<ul class=\"slider-img-ul\">\r\n");
      out.write("\t\t\t<li><img src=\"images/digua.jpg\"></li>\r\n");
      out.write("\t\t\t<li><img src=\"images/banala.jpg\"></li>\r\n");
      out.write("\t\t\t<li><img src=\"images/timg.jpg\"></li>\r\n");
      out.write("\t\t\t<li><img src=\"images/huanggua.jpg\"></li>\r\n");
      out.write("\t\t\t<li><img src=\"images/liulian.jpg\"></li>\r\n");
      out.write("\t\t\t<li><img src=\"images/80.jpg\"></li>\r\n");
      out.write("\t\t\t<li><img src=\"images/huanggua.jpg\"></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script src=\"js/jquery-1.11.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/xSlider.js\"></script>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"gwcServlet\" method=\"post\">\r\n");
      out.write("\t\t<div id=\"big_div\">\r\n");
      out.write("\t\t ");

			 Object obj3=request.getAttribute("cates");
			 if(obj3!=null)
			 {
	        	  PageModel<Product> pageModel=(PageModel<Product>)obj3;
	        	  for(int i=0;i<pageModel.getDatas().size();i++){
	        		  
	        		  
      out.write("\r\n");
      out.write("\t\t\t<div class=\"div_1\">\r\n");
      out.write("\t\t\t<input hidden=\"hidden\" value=\"");
      out.print(pageModel.getDatas().get(i).getCid() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t<div class=\"img\"><img src=\"img/");
      out.print(pageModel.getDatas().get(i).getPic() );
      out.write("\"/></div>\r\n");
      out.write("\t\t\t\t<p>");
      out.print(pageModel.getDatas().get(i).getPname() );
      out.write("</p></br>\r\n");
      out.write("\t\t\t   <input name=\"pname\" hidden=\"hidden\" value=\"");
      out.print(pageModel.getDatas().get(i).getPname() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<span hidden=\"hidden\">详情：");
      out.print(pageModel.getDatas().get(i).getPdetail() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t<input hidden=\"hidden\" value=\"");
      out.print(pageModel.getDatas().get(i).getOnline() );
      out.write("\"/>该上商品已经上线\r\n");
      out.write("\t\t\t\t<input  name=\"pno\" hidden=\"hidden\" value=\"");
      out.print(pageModel.getDatas().get(i).getPno() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t<p>￥");
      out.print(pageModel.getDatas().get(i).getPrice() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t<input name=\"price\" hidden=\"hidden\" value=\"");
      out.print(pageModel.getDatas().get(i).getPrice() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t<p class=\"shuliang\"><span>数量</span><input name=\"shuliang\" type=\"text\"/><button>购买</button></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t ");
  
	        		  
	        	  }  
	        	  
			 
			 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"page\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t共");
      out.print(pageModel.getTotalcount() );
      out.write("条记录&nbsp;");
      out.print(pageModel.getPageNo() );
      out.write('/');
      out.print(pageModel.getTotalPageSize() );
      out.write("页&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<a href=\"getProPage?pageNo=1&pageSize=7\">首页</a>\r\n");
      out.write("\t\t\t<a href=\"getProPage?pageNo=");
      out.print(pageModel.getPageNo()-1==0?pageModel.getPageNo():pageModel.getPageNo()-1);
      out.write("&pageSize=7\">下页</a>\r\n");
      out.write("\t\t\t<a href=\"getProPage?pageNo=");
      out.print(pageModel.getPageNo()+1==pageModel.getTotalPageSize()+1?pageModel.getTotalPageSize():pageModel.getPageNo()+1 );
      out.write("&pageSize=7\">上页</a>\r\n");
      out.write("\t\t    <a href=\"getProPage?pageNo=");
      out.print(pageModel.getTotalPageSize() );
      out.write("&pageSize=7\">尾页</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t第&nbsp;<select onChange=\"if(this.value==this.options[this.options.selectedIndex].value){location='getProPage?&pageNo='+this.value+'&pageSize=7'}\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 
				if(pageModel!=null){
		        	   int _totalPageSize=pageModel.getTotalPageSize();
		        	   for(int i=0;i<_totalPageSize;i++){
		        		   
		        		   if(pageModel.getPageNo()==(i+1)){
      out.write("\r\n");
      out.write("\t        \t\t    \t\r\n");
      out.write("\t\t        \t\t    <option value=\"");
      out.print(i+1 );
      out.write("\" selected=\"selected\">");
      out.print((i+1));
      out.write("</option>\r\n");
      out.write("\t\t        \t\t  ");
  }else{
      out.write("\r\n");
      out.write("\t\t        \t\t\t  <option value=\"");
      out.print(i+1 );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print((i+1));
      out.write("</option>\r\n");
      out.write("\t\t        \t\t  ");
}
		        	   }
		        	   
				}
				
				
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</select>&nbsp;页\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  ");
}
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
